[package]
name = "arthroprod"
version = "0.1.2"
authors = ["sminez <innes@cocoon.life>"]

[[bin]]
doc = false
name = "ar"
path = "src/bin/main.rs"

[dependencies]
lazy_static = "0.2"

[dev-dependencies]
proptest = "0.3.1"
