[package]
version = "0.1.2"
name = "arthroprod"
authors = ["sminez <innes@cocoon.life>"]
license = "MIT"
license-file = "LICENSE"
repository = "https://github.com/sminez/arthroprod"
documentation = "https://docs.rs/arthroprod"
readme = "README.md"

[[bin]]
doc = false
name = "ar"
path = "src/bin/main.rs"

[dependencies]
lazy_static = "0.2"

[dev-dependencies]
proptest = "0.3.1"
